Modifications in line with latest cargo vendor tool
openSUSE/obs-service-source_validator pull request #129
Opened 2023-11-01 00:58 UTC by Firstyear

Cargo vendor has been rewritten in rust and now absorbs the functionality of cargo-audit in a way that it can not be bypassed.

As a result the strict cargo audit check is now not needed as it's enforced on packages that vendor. 

Additionally some of the semantics around cargo update have changed, which this now reflects.

2023-12-18 10:01 UTC, jubalh commented
@dirkmueller could you maybe have a look at this one? :)

2024-01-14 11:35 UTC, uncomfyhalomacro commented
bump @dirkmueller

2024-02-07 02:04 UTC, xtexChooser commented
plsssss merge thissss

2024-02-23 12:22 UTC, JanZerebecki requested changes
This is still broken and would prevent submitting security fixes.

2024-03-28 09:55 UTC, dirkmueller approved these changes

2024-03-28 09:55 UTC, merged