Fix running the checks on a directory with whitespace in its path
openSUSE/obs-service-source_validator pull request #75
Opened 2019-01-02 19:05 UTC by theMarix

2020-11-20 16:53 UTC, ddiss requested changes
Looks like obvious goodness to me. @theMarix please rebase and then I'll try to track down a maintainer to get this merged. Thanks!

2020-11-20 19:07 UTC, theMarix commented
Thanks for picking this up, @ddiss . Rebase is done.

2020-11-21 00:40 UTC, ddiss commented on 45-stale-changes
>  DESTINATIONDIR=$2
Thanks for the respin - should the `DESTINATIONDIR` assignment be quoted here too?

2020-11-21 00:40 UTC, ddiss commented on 70-baselibs
>  DESTINATIONDIR=$2
Same for above

2020-11-22 12:56 UTC, theMarix commented on 45-stale-changes
>  DESTINATIONDIR=$2
In my tests this did not show up as an issue. But simply for consistency we should. And maybe somebody has an even more weird set-up than mine so it'll actually help.

2020-11-22 18:18 UTC, ddiss approved these changes
Looks good - thanks again for your contribution!
@adrianschroeter which maintainer should I ping to get this merged?

2020-12-20 17:47 UTC, ddiss commented
> @adrianschroeter which maintainer should I ping to get this merged?

Ping - @sjamgade @bugfinder anyone else able to merge this?

2021-09-17 08:38 UTC, merged